# Auto-generated environment configuration
# Generated by setup-env.ps1

$env:CLANG_PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin\clang.exe"
$env:VS_PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community"
$env:VCVARS_PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
$env:CLANG_DIR = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin"
# Add tools to PATH if not already present
if ($env:PATH -notlike "*C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64*") {
    $env:PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64;" + $env:PATH
}
if ($env:PATH -notlike "*C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin*") {
    $env:PATH = "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\bin;" + $env:PATH
}
